"""empty message

Revision ID: 09e6bcbca830
Revises: 52a6aaafb1b3
Create Date: 2018-09-29 15:36:24.879271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e6bcbca830'
down_revision = '52a6aaafb1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seat', sa.Column('note', sa.String(), nullable=True))
    op.add_column('video', sa.Column('code_rate', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('fhd_url', sa.String(), nullable=True))
    op.add_column('video', sa.Column('hd_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'hd_url')
    op.drop_column('video', 'fhd_url')
    op.drop_column('video', 'code_rate')
    op.drop_column('seat', 'note')
    # ### end Alembic commands ###
