"""empty message

Revision ID: 0e3d692aa784
Revises: b448c08eaec5
Create Date: 2018-08-08 21:11:16.223631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3d692aa784'
down_revision = 'b448c08eaec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach', sa.Column('not_in_service_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach', 'not_in_service_at')
    # ### end Alembic commands ###
