"""empty message

Revision ID: 0f281678f466
Revises: 0f4021c7ef76
Create Date: 2018-12-24 20:30:07.430574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f281678f466'
down_revision = '0f4021c7ef76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_biz_id'), 'contract', ['biz_id'], unique=False)
    op.create_index(op.f('ix_contract_phone_number'), 'contract', ['phone_number'], unique=False)
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('course_name', sa.String(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('attended', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainee_id', 'course_name', name='_lesson_trainee_id_course_name')
    )
    op.create_index(op.f('ix_lesson_customer_id'), 'lesson', ['customer_id'], unique=False)
    op.create_index(op.f('ix_lesson_trainee_id'), 'lesson', ['trainee_id'], unique=False)
    op.add_column('department', sa.Column('is_root', sa.Boolean(), nullable=True))
    op.add_column('seat', sa.Column('checked_at', sa.DateTime(), nullable=True))
    op.add_column('seat', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('seat', sa.Column('course_name', sa.String(), nullable=True))
    op.add_column('seat', sa.Column('is_check', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seat', 'is_check')
    op.drop_column('seat', 'course_name')
    op.drop_column('seat', 'course_id')
    op.drop_column('seat', 'checked_at')
    op.drop_column('department', 'is_root')
    op.drop_index(op.f('ix_lesson_trainee_id'), table_name='lesson')
    op.drop_index(op.f('ix_lesson_customer_id'), table_name='lesson')
    op.drop_table('lesson')
    op.drop_index(op.f('ix_contract_phone_number'), table_name='contract')
    op.drop_index(op.f('ix_contract_biz_id'), table_name='contract')
    op.drop_table('contract')
    # ### end Alembic commands ###
