"""empty message

Revision ID: 11ffe35fdada
Revises: 16aa0b032130
Create Date: 2018-08-20 17:22:17.395682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11ffe35fdada'
down_revision = '16aa0b032130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('courses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_biz_id'), 'place', ['biz_id'], unique=False)
    op.create_table('reserve_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('exp_date', sa.DateTime(), nullable=True),
    sa.Column('exp_time', sa.Integer(), nullable=True),
    sa.Column('e_mail', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reserve_email_biz_id'), 'reserve_email', ['biz_id'], unique=False)
    op.create_table('thumb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('feed_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thumb_biz_id'), 'thumb', ['biz_id'], unique=False)
    op.create_index(op.f('ix_thumb_customer_id'), 'thumb', ['customer_id'], unique=False)
    op.create_index(op.f('ix_thumb_feed_id'), 'thumb', ['feed_id'], unique=False)
    op.create_index(op.f('ix_thumb_video_id'), 'thumb', ['video_id'], unique=False)
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('poster', sa.String(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('video_type', sa.String(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('classification_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('video_info', sa.JSON(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_biz_id'), 'video', ['biz_id'], unique=False)
    op.create_index(op.f('ix_video_file_id'), 'video', ['file_id'], unique=False)
    op.create_index(op.f('ix_video_place_id'), 'video', ['place_id'], unique=False)
    op.add_column('feed', sa.Column('coach_id', sa.Integer(), nullable=True))
    op.add_column('feed', sa.Column('video', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('ix_group_course_coach_id', table_name='group_course')
    op.drop_index('ix_group_course_course_id', table_name='group_course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_group_course_course_id', 'group_course', ['course_id'], unique=False)
    op.create_index('ix_group_course_coach_id', 'group_course', ['coach_id'], unique=False)
    op.drop_column('feed', 'video')
    op.drop_column('feed', 'coach_id')
    op.drop_index(op.f('ix_video_place_id'), table_name='video')
    op.drop_index(op.f('ix_video_file_id'), table_name='video')
    op.drop_index(op.f('ix_video_biz_id'), table_name='video')
    op.drop_table('video')
    op.drop_index(op.f('ix_thumb_video_id'), table_name='thumb')
    op.drop_index(op.f('ix_thumb_feed_id'), table_name='thumb')
    op.drop_index(op.f('ix_thumb_customer_id'), table_name='thumb')
    op.drop_index(op.f('ix_thumb_biz_id'), table_name='thumb')
    op.drop_table('thumb')
    op.drop_index(op.f('ix_reserve_email_biz_id'), table_name='reserve_email')
    op.drop_table('reserve_email')
    op.drop_index(op.f('ix_place_biz_id'), table_name='place')
    op.drop_table('place')
    # ### end Alembic commands ###
