"""empty message

Revision ID: 143120a8d834
Revises: 777343037432
Create Date: 2019-01-04 15:42:48.976224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '143120a8d834'
down_revision = '777343037432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficiary_biz_id'), 'beneficiary', ['biz_id'], unique=False)
    op.create_index(op.f('ix_beneficiary_contract_id'), 'beneficiary', ['contract_id'], unique=False)
    op.create_table('contract_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('attended', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_content_contract_id'), 'contract_content', ['contract_id'], unique=False)
    op.create_table('seat_check_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_id', sa.Integer(), nullable=True),
    sa.Column('seat_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seat_check_log_biz_id'), 'seat_check_log', ['biz_id'], unique=False)
    op.create_index(op.f('ix_seat_check_log_id'), 'seat_check_log', ['id'], unique=False)
    op.drop_index('ix_lesson_customer_id', table_name='lesson')
    op.drop_index('ix_lesson_trainee_id', table_name='lesson')
    op.drop_table('lesson')
    op.add_column('contract', sa.Column('is_group', sa.Boolean(), nullable=True))
    op.drop_index('ix_contract_phone_number', table_name='contract')
    op.drop_column('contract', 'phone_number')
    op.drop_column('contract', 'name')
    op.add_column('seat', sa.Column('is_group', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seat', 'is_group')
    op.add_column('contract', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contract', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_contract_phone_number', 'contract', ['phone_number'], unique=False)
    op.drop_column('contract', 'is_group')
    op.create_table('lesson',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trainee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attended', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='lesson_pkey'),
    sa.UniqueConstraint('trainee_id', 'course_id', name='_lesson_trainee_id_course_id')
    )
    op.create_index('ix_lesson_trainee_id', 'lesson', ['trainee_id'], unique=False)
    op.create_index('ix_lesson_customer_id', 'lesson', ['customer_id'], unique=False)
    op.drop_index(op.f('ix_seat_check_log_id'), table_name='seat_check_log')
    op.drop_index(op.f('ix_seat_check_log_biz_id'), table_name='seat_check_log')
    op.drop_table('seat_check_log')
    op.drop_index(op.f('ix_contract_content_contract_id'), table_name='contract_content')
    op.drop_table('contract_content')
    op.drop_index(op.f('ix_beneficiary_contract_id'), table_name='beneficiary')
    op.drop_index(op.f('ix_beneficiary_biz_id'), table_name='beneficiary')
    op.drop_table('beneficiary')
    # ### end Alembic commands ###
