"""empty message

Revision ID: 1a69dc62db8c
Revises: 4a0fc41deee4
Create Date: 2018-06-23 14:50:04.940520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a69dc62db8c'
down_revision = '4a0fc41deee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_biz', sa.Column('related_biz_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_biz', 'related_biz_id')
    # ### end Alembic commands ###
