"""empty message

Revision ID: 1ac2fa705d52
Revises: 4f666bd7f2be
Create Date: 2018-06-29 22:20:18.183881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ac2fa705d52'
down_revision = '4f666bd7f2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('attend_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('is_break', sa.Boolean(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('reserved_at', sa.DateTime(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seat_coach_id'), 'seat', ['coach_id'], unique=False)
    op.create_index(op.f('ix_seat_day'), 'seat', ['day'], unique=False)
    op.create_table('trainee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('remained_lessons', sa.Integer(), nullable=True),
    sa.Column('attended_lessons', sa.Integer(), nullable=True),
    sa.Column('bind_at', sa.DateTime(), nullable=True),
    sa.Column('unbind_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_id', 'customer_id', name='_coach_id_customer_id')
    )
    op.create_index(op.f('ix_trainee_coach_id'), 'trainee', ['coach_id'], unique=False)
    op.drop_index('ix_binding_biz_id', table_name='binding')
    op.drop_index('ix_binding_coach_id', table_name='binding')
    op.drop_index('ix_binding_customer_id', table_name='binding')
    op.drop_table('binding')
    op.create_index(op.f('ix_group_course_biz_id'), 'group_course', ['biz_id'], unique=False)
    op.create_index(op.f('ix_group_course_coach_id'), 'group_course', ['coach_id'], unique=False)
    op.create_index(op.f('ix_group_course_course_id'), 'group_course', ['course_id'], unique=False)
    op.create_index(op.f('ix_group_course_group_time_id'), 'group_course', ['group_time_id'], unique=False)
    op.drop_index('ix_group_courses_biz_id', table_name='group_course')
    op.drop_index('ix_group_courses_coach_id', table_name='group_course')
    op.drop_index('ix_group_courses_courses_id', table_name='group_course')
    op.drop_index('ix_group_courses_group_time_id', table_name='group_course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_group_courses_group_time_id', 'group_course', ['group_time_id'], unique=False)
    op.create_index('ix_group_courses_courses_id', 'group_course', ['course_id'], unique=False)
    op.create_index('ix_group_courses_coach_id', 'group_course', ['coach_id'], unique=False)
    op.create_index('ix_group_courses_biz_id', 'group_course', ['biz_id'], unique=False)
    op.drop_index(op.f('ix_group_course_group_time_id'), table_name='group_course')
    op.drop_index(op.f('ix_group_course_course_id'), table_name='group_course')
    op.drop_index(op.f('ix_group_course_coach_id'), table_name='group_course')
    op.drop_index(op.f('ix_group_course_biz_id'), table_name='group_course')
    op.create_table('binding',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('biz_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coach_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('real_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='binding_pkey')
    )
    op.create_index('ix_binding_customer_id', 'binding', ['customer_id'], unique=False)
    op.create_index('ix_binding_coach_id', 'binding', ['coach_id'], unique=False)
    op.create_index('ix_binding_biz_id', 'binding', ['biz_id'], unique=False)
    op.drop_index(op.f('ix_trainee_coach_id'), table_name='trainee')
    op.drop_table('trainee')
    op.drop_index(op.f('ix_seat_day'), table_name='seat')
    op.drop_index(op.f('ix_seat_coach_id'), table_name='seat')
    op.drop_table('seat')
    op.drop_table('private_lesson')
    # ### end Alembic commands ###
