"""empty message

Revision ID: 1cb6cc297ff7
Revises: 0e3d692aa784
Create Date: 2018-08-10 15:32:49.984104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb6cc297ff7'
down_revision = '0e3d692aa784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wx_authorizer', sa.Column('setting', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wx_authorizer', 'setting')
    # ### end Alembic commands ###
