"""empty message

Revision ID: 24e920e9fe52
Revises: 48c14dcffbc1
Create Date: 2018-12-14 17:01:33.783762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e920e9fe52'
down_revision = '48c14dcffbc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('operating_object_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('operated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_log_biz_id'), 'operation_log', ['biz_id'], unique=False)
    op.create_index(op.f('ix_operation_log_operating_object_id'), 'operation_log', ['operating_object_id'], unique=False)
    op.create_index(op.f('ix_operation_log_operator_id'), 'operation_log', ['operator_id'], unique=False)
    op.add_column('trainee', sa.Column('accepted_at', sa.DateTime(), nullable=True))
    op.add_column('trainee', sa.Column('is_exp', sa.Boolean(), nullable=True))
    op.add_column('trainee', sa.Column('is_measurements', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainee', 'is_measurements')
    op.drop_column('trainee', 'is_exp')
    op.drop_column('trainee', 'accepted_at')
    op.drop_index(op.f('ix_operation_log_operator_id'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_operating_object_id'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_biz_id'), table_name='operation_log')
    op.drop_table('operation_log')
    # ### end Alembic commands ###
