"""empty message

Revision ID: 28b94fc546ea
Revises: 66dd5df0b86e
Create Date: 2018-12-12 15:30:38.226294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28b94fc546ea'
down_revision = '66dd5df0b86e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ex_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ex_id', sa.Integer(), nullable=True),
    sa.Column('ex_title', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('diary_id', sa.Integer(), nullable=True),
    sa.Column('diary_date', sa.DateTime(), nullable=False),
    sa.Column('sets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('work', sa.Float(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ex_history_customer_id'), 'ex_history', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ex_history_ex_id'), 'ex_history', ['ex_id'], unique=False)
    op.create_index(op.f('ix_ex_history_ex_title'), 'ex_history', ['ex_title'], unique=False)
    op.create_index(op.f('ix_ex_history_recorded_at'), 'ex_history', ['recorded_at'], unique=False)
    op.create_table('ex_property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ex_id', sa.Integer(), nullable=True),
    sa.Column('ex_title', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('record_method', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('last_recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ex_id', 'ex_title', 'customer_id', name='_ex_property_ex')
    )
    op.create_index(op.f('ix_ex_property_customer_id'), 'ex_property', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ex_property_ex_id'), 'ex_property', ['ex_id'], unique=False)
    op.create_index(op.f('ix_ex_property_ex_title'), 'ex_property', ['ex_title'], unique=False)
    op.drop_table('ex_in_workout')
    op.drop_table('ex_viewed')
    op.add_column('diary', sa.Column('workout', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary', 'workout')
    op.create_table('ex_viewed',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ex_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('viewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ex_viewed_pkey')
    )
    op.create_table('ex_in_workout',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ex_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sets', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('work', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('record_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('common_unit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ex_in_workout_pkey')
    )
    op.drop_index(op.f('ix_ex_property_ex_title'), table_name='ex_property')
    op.drop_index(op.f('ix_ex_property_ex_id'), table_name='ex_property')
    op.drop_index(op.f('ix_ex_property_customer_id'), table_name='ex_property')
    op.drop_table('ex_property')
    op.drop_index(op.f('ix_ex_history_recorded_at'), table_name='ex_history')
    op.drop_index(op.f('ix_ex_history_ex_title'), table_name='ex_history')
    op.drop_index(op.f('ix_ex_history_ex_id'), table_name='ex_history')
    op.drop_index(op.f('ix_ex_history_customer_id'), table_name='ex_history')
    op.drop_table('ex_history')
    # ### end Alembic commands ###
