"""empty message

Revision ID: 48c14dcffbc1
Revises: 28b94fc546ea
Create Date: 2018-12-14 11:07:45.611987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c14dcffbc1'
down_revision = '28b94fc546ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_diary_customer_id_recorded_at', 'diary', ['customer_id', 'recorded_at'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_diary_customer_id_recorded_at', 'diary', type_='unique')
    # ### end Alembic commands ###
