"""empty message

Revision ID: 4a0fc41deee4
Revises: 53eb51c478ee
Create Date: 2018-06-20 11:25:56.708319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0fc41deee4'
down_revision = '53eb51c478ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_id', sa.Integer(), nullable=True),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('real_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_binding_biz_id'), 'binding', ['biz_id'], unique=False)
    op.create_index(op.f('ix_binding_coach_id'), 'binding', ['coach_id'], unique=False)
    op.create_index(op.f('ix_binding_customer_id'), 'binding', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_binding_customer_id'), table_name='binding')
    op.drop_index(op.f('ix_binding_coach_id'), table_name='binding')
    op.drop_index(op.f('ix_binding_biz_id'), table_name='binding')
    op.drop_table('binding')
    # ### end Alembic commands ###
