"""empty message

Revision ID: 4f666bd7f2be
Revises: 1a69dc62db8c
Create Date: 2018-06-28 10:37:05.996882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f666bd7f2be'
down_revision = '1a69dc62db8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach', sa.Column('coach_type', sa.String(), nullable=True))
    op.add_column('coach', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('course', sa.Column('course_type', sa.String(), nullable=True))
    op.add_column('wx_open_user', sa.Column('coach_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wx_open_user', 'coach_id')
    op.drop_column('course', 'course_type')
    op.drop_column('coach', 'phone_number')
    op.drop_column('coach', 'coach_type')
    # ### end Alembic commands ###
