"""empty message

Revision ID: 52a6aaafb1b3
Revises: 58c1f30a04c8
Create Date: 2018-09-26 11:37:34.135291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a6aaafb1b3'
down_revision = '58c1f30a04c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('mini_salesman_id', sa.Integer(), nullable=True),
    sa.Column('belong_salesman_name', sa.String(), nullable=True),
    sa.Column('reservation_date', sa.DateTime(), nullable=True),
    sa.Column('reservation_time', sa.Integer(), nullable=True),
    sa.Column('is_arrived', sa.Boolean(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_biz_id'), 'registration', ['biz_id'], unique=False)
    op.create_index(op.f('ix_registration_mini_salesman_id'), 'registration', ['mini_salesman_id'], unique=False)
    op.add_column('customer', sa.Column('name', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'tags')
    op.drop_column('customer', 'name')
    op.drop_index(op.f('ix_registration_mini_salesman_id'), table_name='registration')
    op.drop_index(op.f('ix_registration_biz_id'), table_name='registration')
    op.drop_table('registration')
    # ### end Alembic commands ###
