"""empty message

Revision ID: 53eb51c478ee
Revises: 8fe6e79b0c2d
Create Date: 2018-06-19 16:00:22.559394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53eb51c478ee'
down_revision = '8fe6e79b0c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wx_open_user', 'app_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('_open_id_app_id', 'wx_open_user', ['wx_open_id', 'app_id'])
    op.drop_constraint('_open_id_biz_id', 'wx_open_user', type_='unique')
    op.drop_index('ix_wx_open_user_biz_id', table_name='wx_open_user')
    op.drop_column('wx_open_user', 'biz_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wx_open_user', sa.Column('biz_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_wx_open_user_biz_id', 'wx_open_user', ['biz_id'], unique=False)
    op.create_unique_constraint('_open_id_biz_id', 'wx_open_user', ['wx_open_id', 'biz_id'])
    op.drop_constraint('_open_id_app_id', 'wx_open_user', type_='unique')
    op.alter_column('wx_open_user', 'app_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
