"""empty message

Revision ID: 58c1f30a04c8
Revises: 4c7b4e707683
Create Date: 2018-09-19 15:20:48.895978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c1f30a04c8'
down_revision = '4c7b4e707683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('is_common', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'is_common')
    # ### end Alembic commands ###
