"""empty message

Revision ID: 66dd5df0b86e
Revises: a392281d3567
Create Date: 2018-12-05 11:38:16.302297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66dd5df0b86e'
down_revision = 'a392281d3567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('pictures', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_mg', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('secondary_mg', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('describe', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_exs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('record_method', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_table('ex_in_workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ex_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('work', sa.Float(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('record_method', sa.String(), nullable=True),
    sa.Column('common_unit', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ex_viewed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ex_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ex_viewed')
    op.drop_table('ex_in_workout')
    op.drop_table('ex')
    # ### end Alembic commands ###
