"""empty message

Revision ID: 71181a08d022
Revises: 90641dc534ac
Create Date: 2019-01-09 10:39:35.549453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71181a08d022'
down_revision = '90641dc534ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_wall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_wall_biz_id'), 'photo_wall', ['biz_id'], unique=False)
    op.create_index(op.f('ix_photo_wall_coach_id'), 'photo_wall', ['coach_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_wall_coach_id'), table_name='photo_wall')
    op.drop_index(op.f('ix_photo_wall_biz_id'), table_name='photo_wall')
    op.drop_table('photo_wall')
    # ### end Alembic commands ###
