"""empty message

Revision ID: 76ef6b5a6c9d
Revises: 746cfc934ca7
Create Date: 2018-07-17 21:13:16.535879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ef6b5a6c9d'
down_revision = '746cfc934ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_check_in_check_in_date'), 'check_in', ['check_in_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_in_check_in_date'), table_name='check_in')
    # ### end Alembic commands ###
