"""empty message

Revision ID: 8fe6e79b0c2d
Revises: 
Create Date: 2018-06-19 15:44:13.555937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fe6e79b0c2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biz_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biz_user_phone_number'), 'biz_user', ['phone_number'], unique=True)
    op.create_table('check_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('check_in_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_in_biz_id'), 'check_in', ['biz_id'], unique=False)
    op.create_index(op.f('ix_check_in_customer_id'), 'check_in', ['customer_id'], unique=False)
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_id', sa.Integer(), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('words', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_biz_id'), 'feed', ['biz_id'], unique=False)
    op.create_table('group_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_id', sa.Integer(), nullable=True),
    sa.Column('group_time_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('courses_id', sa.Integer(), nullable=True),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_courses_biz_id'), 'group_courses', ['biz_id'], unique=False)
    op.create_index(op.f('ix_group_courses_coach_id'), 'group_courses', ['coach_id'], unique=False)
    op.create_index(op.f('ix_group_courses_courses_id'), 'group_courses', ['courses_id'], unique=False)
    op.create_index(op.f('ix_group_courses_group_time_id'), 'group_courses', ['group_time_id'], unique=False)
    op.create_table('group_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_time_biz_id'), 'group_time', ['biz_id'], unique=False)
    op.create_table('qrcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('is_limit', sa.Boolean(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('scene', sa.String(), nullable=True),
    sa.Column('page', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('auto_color', sa.Boolean(), nullable=True),
    sa.Column('line_color', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_hyaline', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'app_id', name='_name_app_id')
    )
    op.create_index(op.f('ix_qrcode_app_id'), 'qrcode', ['app_id'], unique=False)
    op.create_table('store_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('wx_template_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('ext_json_format', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('params_desc', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('customer', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('nick_name', sa.String(), nullable=True))
    op.add_column('store', sa.Column('template_id', sa.Integer(), nullable=True))
    op.add_column('store_biz', sa.Column('audit_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('store_biz', sa.Column('audit_time', sa.DateTime(), nullable=True))
    op.add_column('store_biz', sa.Column('auto_release', sa.Boolean(), nullable=True))
    op.add_column('store_biz', sa.Column('biz_user_id', sa.Integer(), nullable=True))
    op.add_column('store_biz', sa.Column('check_info_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('store_biz', sa.Column('check_info_time', sa.DateTime(), nullable=True))
    op.add_column('store_biz', sa.Column('commit', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('store_biz', sa.Column('commit_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('store_biz', sa.Column('commit_time', sa.DateTime(), nullable=True))
    op.add_column('store_biz', sa.Column('release', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('store_biz', sa.Column('release_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('store_biz', sa.Column('release_time', sa.DateTime(), nullable=True))
    op.add_column('store_biz', sa.Column('set_db', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('store_biz', sa.Column('set_db_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('store_biz', sa.Column('set_db_time', sa.DateTime(), nullable=True))
    op.add_column('store_biz', sa.Column('set_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('store_biz', sa.Column('set_template_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('store_biz', sa.Column('set_template_time', sa.DateTime(), nullable=True))
    op.add_column('store_biz', sa.Column('submit', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('store_biz', sa.Column('submit_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('store_biz', sa.Column('submit_time', sa.DateTime(), nullable=True))
    op.add_column('store_biz', sa.Column('wx_authorizer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_store_biz_biz_user_id'), 'store_biz', ['biz_user_id'], unique=False)
    op.drop_index('ix_store_biz_app_id', table_name='store_biz')
    op.create_unique_constraint(None, 'store_biz', ['wx_authorizer_id'])
    op.create_foreign_key(None, 'store_biz', 'wx_authorizer', ['wx_authorizer_id'], ['id'])
    op.drop_column('store_biz', 'app_id')
    op.drop_index('ix_wx_authorizer_app_id', table_name='wx_authorizer')
    op.create_index(op.f('ix_wx_authorizer_app_id'), 'wx_authorizer', ['app_id'], unique=True)
    op.add_column('wx_open_user', sa.Column('app_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_wx_open_user_app_id'), 'wx_open_user', ['app_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wx_open_user_app_id'), table_name='wx_open_user')
    op.drop_column('wx_open_user', 'app_id')
    op.drop_index(op.f('ix_wx_authorizer_app_id'), table_name='wx_authorizer')
    op.create_index('ix_wx_authorizer_app_id', 'wx_authorizer', ['app_id'], unique=False)
    op.add_column('store_biz', sa.Column('app_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'store_biz', type_='foreignkey')
    op.drop_constraint(None, 'store_biz', type_='unique')
    op.create_index('ix_store_biz_app_id', 'store_biz', ['app_id'], unique=True)
    op.drop_index(op.f('ix_store_biz_biz_user_id'), table_name='store_biz')
    op.drop_column('store_biz', 'wx_authorizer_id')
    op.drop_column('store_biz', 'submit_time')
    op.drop_column('store_biz', 'submit_result')
    op.drop_column('store_biz', 'submit')
    op.drop_column('store_biz', 'set_template_time')
    op.drop_column('store_biz', 'set_template_result')
    op.drop_column('store_biz', 'set_template')
    op.drop_column('store_biz', 'set_db_time')
    op.drop_column('store_biz', 'set_db_result')
    op.drop_column('store_biz', 'set_db')
    op.drop_column('store_biz', 'release_time')
    op.drop_column('store_biz', 'release_result')
    op.drop_column('store_biz', 'release')
    op.drop_column('store_biz', 'commit_time')
    op.drop_column('store_biz', 'commit_result')
    op.drop_column('store_biz', 'commit')
    op.drop_column('store_biz', 'check_info_time')
    op.drop_column('store_biz', 'check_info_result')
    op.drop_column('store_biz', 'biz_user_id')
    op.drop_column('store_biz', 'auto_release')
    op.drop_column('store_biz', 'audit_time')
    op.drop_column('store_biz', 'audit_result')
    op.drop_column('store', 'template_id')
    op.drop_column('customer', 'nick_name')
    op.drop_column('customer', 'avatar')
    op.drop_table('store_template')
    op.drop_index(op.f('ix_qrcode_app_id'), table_name='qrcode')
    op.drop_table('qrcode')
    op.drop_index(op.f('ix_group_time_biz_id'), table_name='group_time')
    op.drop_table('group_time')
    op.drop_index(op.f('ix_group_courses_group_time_id'), table_name='group_courses')
    op.drop_index(op.f('ix_group_courses_courses_id'), table_name='group_courses')
    op.drop_index(op.f('ix_group_courses_coach_id'), table_name='group_courses')
    op.drop_index(op.f('ix_group_courses_biz_id'), table_name='group_courses')
    op.drop_table('group_courses')
    op.drop_index(op.f('ix_feed_biz_id'), table_name='feed')
    op.drop_table('feed')
    op.drop_index(op.f('ix_check_in_customer_id'), table_name='check_in')
    op.drop_index(op.f('ix_check_in_biz_id'), table_name='check_in')
    op.drop_table('check_in')
    op.drop_index(op.f('ix_biz_user_phone_number'), table_name='biz_user')
    op.drop_table('biz_user')
    # ### end Alembic commands ###
