"""empty message

Revision ID: 90641dc534ac
Revises: 143120a8d834
Create Date: 2019-01-08 10:40:30.553965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90641dc534ac'
down_revision = '143120a8d834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('operated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_log_biz_id'), 'contract_log', ['biz_id'], unique=False)
    op.create_index(op.f('ix_contract_log_contract_id'), 'contract_log', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_log_id'), 'contract_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_log_id'), table_name='contract_log')
    op.drop_index(op.f('ix_contract_log_contract_id'), table_name='contract_log')
    op.drop_index(op.f('ix_contract_log_biz_id'), table_name='contract_log')
    op.drop_table('contract_log')
    # ### end Alembic commands ###
