"""empty message

Revision ID: 9954baddb24e
Revises: c5578489a069
Create Date: 2018-08-02 21:43:45.714245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9954baddb24e'
down_revision = 'c5578489a069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach', sa.Column('permission_list', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach', 'permission_list')
    # ### end Alembic commands ###
