"""empty message

Revision ID: 9a48397db36d
Revises: 11ffe35fdada
Create Date: 2018-08-25 10:52:45.265344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a48397db36d'
down_revision = '11ffe35fdada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_course', sa.Column('place_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_group_course_place_id'), 'group_course', ['place_id'], unique=False)
    op.add_column('reserve_email', sa.Column('email_address', sa.String(), nullable=True))
    op.drop_column('reserve_email', 'e_mail')
    op.add_column('video', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('is_valid', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_video_course_id'), 'video', ['course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_course_id'), table_name='video')
    op.drop_column('video', 'is_valid')
    op.drop_column('video', 'course_id')
    op.add_column('reserve_email', sa.Column('e_mail', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('reserve_email', 'email_address')
    op.drop_index(op.f('ix_group_course_place_id'), table_name='group_course')
    op.drop_column('group_course', 'place_id')
    # ### end Alembic commands ###
