"""empty message

Revision ID: b2cf7641fbb2
Revises: 43315b3642d3
Create Date: 2018-09-11 18:19:29.291995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2cf7641fbb2'
down_revision = '43315b3642d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach', sa.Column('videos', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('course', sa.Column('videos', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('customer', sa.Column('from_share_id', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('is_login', sa.Boolean(), nullable=True))
    op.add_column('customer', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('place', sa.Column('videos', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('video', sa.Column('coaches', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('video', sa.Column('courses', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('video', sa.Column('places', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('video', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('ix_video_course_id', table_name='video')
    op.drop_index('ix_video_place_id', table_name='video')
    op.drop_column('video', 'course_id')
    op.drop_column('video', 'place_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('place_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('video', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_video_place_id', 'video', ['place_id'], unique=False)
    op.create_index('ix_video_course_id', 'video', ['course_id'], unique=False)
    op.drop_column('video', 'tags')
    op.drop_column('video', 'places')
    op.drop_column('video', 'courses')
    op.drop_column('video', 'coaches')
    op.drop_column('place', 'videos')
    op.drop_column('customer', 'phone_number')
    op.drop_column('customer', 'is_login')
    op.drop_column('customer', 'from_share_id')
    op.drop_column('course', 'videos')
    op.drop_column('coach', 'videos')
    # ### end Alembic commands ###
