"""empty message

Revision ID: b448c08eaec5
Revises: 9954baddb24e
Create Date: 2018-08-04 15:58:02.036453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b448c08eaec5'
down_revision = '9954baddb24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach', sa.Column('in_service', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach', 'in_service')
    # ### end Alembic commands ###
