"""empty message

Revision ID: c5578489a069
Revises: 76ef6b5a6c9d
Create Date: 2018-07-30 17:40:06.458716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5578489a069'
down_revision = '76ef6b5a6c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('month_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_id', sa.Integer(), nullable=True),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('yymm', sa.Integer(), nullable=True),
    sa.Column('private_count', sa.Integer(), nullable=True),
    sa.Column('exp_count', sa.Integer(), nullable=True),
    sa.Column('total_lesson', sa.Integer(), nullable=True),
    sa.Column('average', sa.Float(), nullable=True),
    sa.Column('trainee_ranking', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_month_report_coach_id'), 'month_report', ['coach_id'], unique=False)
    op.create_table('seat_trigger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seat_trigger_biz_id'), 'seat_trigger', ['biz_id'], unique=False)
    op.create_table('biz_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_id', sa.Integer(), nullable=False),
    sa.Column('biz_user_id', sa.Integer(), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('permission', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('permission_list', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['biz_user_id'], ['biz_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biz_staff_biz_id'), 'biz_staff', ['biz_id'], unique=False)
    op.create_index(op.f('ix_biz_staff_biz_user_id'), 'biz_staff', ['biz_user_id'], unique=False)
    op.add_column('biz_user', sa.Column('login_at', sa.DateTime(), nullable=True))
    op.add_column('biz_user', sa.Column('name', sa.String(), nullable=True))
    op.add_column('biz_user', sa.Column('token', sa.String(), nullable=True))
    
    op.add_column('coach', sa.Column('exp_price', sa.Integer(), nullable=True))
    op.alter_column('coach', 'coach_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('wx_open_user', sa.Column('token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wx_open_user', 'token')
    op.alter_column('coach', 'coach_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('coach', 'exp_price')
    
    op.drop_column('biz_user', 'token')
    op.drop_column('biz_user', 'name')
    op.drop_column('biz_user', 'login_at')
    op.drop_index(op.f('ix_biz_staff_biz_user_id'), table_name='biz_staff')
    op.drop_index(op.f('ix_biz_staff_biz_id'), table_name='biz_staff')
    op.drop_table('biz_staff')
    op.drop_index(op.f('ix_seat_trigger_biz_id'), table_name='seat_trigger')
    op.drop_table('seat_trigger')
    op.drop_index(op.f('ix_month_report_coach_id'), table_name='month_report')
    op.drop_table('month_report')
    # ### end Alembic commands ###
