"""empty message

Revision ID: d337417e0829
Revises: d435c1ce2d23
Create Date: 2018-11-13 15:42:45.051201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd337417e0829'
down_revision = 'd435c1ce2d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('video_fileid', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'video_fileid')
    # ### end Alembic commands ###
