"""empty message

Revision ID: e32177d0fc2d
Revises: a44ce1603f96
Create Date: 2018-12-26 20:58:13.509563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e32177d0fc2d'
down_revision = 'a44ce1603f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wx_open_user', sa.Column('login_biz_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_wx_open_user_login_biz_id'), 'wx_open_user', ['login_biz_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wx_open_user_login_biz_id'), table_name='wx_open_user')
    op.drop_column('wx_open_user', 'login_biz_id')
    # ### end Alembic commands ###
