"""empty message

Revision ID: e3655be33fba
Revises: f8bde734a04a
Create Date: 2018-10-29 09:24:20.765084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3655be33fba'
down_revision = 'f8bde734a04a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('effective_at', sa.DateTime(), nullable=True))
    op.add_column('coupon', sa.Column('expire_at', sa.DateTime(), nullable=True))
    op.add_column('coupon_report', sa.Column('effective_at', sa.DateTime(), nullable=True))
    op.add_column('registration', sa.Column('belong_salesman_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_registration_belong_salesman_id'), 'registration', ['belong_salesman_id'], unique=False)
    op.add_column('salesman', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salesman', 'email')
    op.drop_index(op.f('ix_registration_belong_salesman_id'), table_name='registration')
    op.drop_column('registration', 'belong_salesman_id')
    op.drop_column('coupon_report', 'effective_at')
    op.drop_column('coupon', 'expire_at')
    op.drop_column('coupon', 'effective_at')
    # ### end Alembic commands ###
