FROM python:3.6

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

RUN mkdir -p /project/websocket

WORKDIR /project/websocket

RUN pip install Flask flask_socketio gunicorn eventlet sentry-sdk[flask]

ADD ws_app.py /project/websocket/